### ISSUE TITLE
How to capture Traffic  monitoring and Network Packets transmission status

### ISSUE THREAD

**Issue by sravanmedarapu** [Juniper/netconf-java#10]
Hi There,

Can some one guide me on capturing below details using netconf-java API

•	Device level error logs (If any commit() action failed now API is throwing "Commit operation returned error" exception, but I would like to capture actual device error msg (logs) as if we are committing it manually) 

•	Traffic  monitoring 

•	Network Packet  Capturing(Some thing like how much data/Packets   has been transferred from one port to another port )

Any help is greatly appreciated

Thanks
Sravan

**Comment by Jainpriyal** [comment]
Hi Sravan,

* Device Logs:
To get the message logs, use getLastRPCReply() method.It will give rpc reply from the device.Use it after functions whose rpc reply you want to see.

* Traffic Monitoring and network Packet Capturing: 
We don't support traffic monitoring and network Packet capturing in Netconf-java. This toolkit only provides classes with methods that implement the functionality of the NETCONF protocol operations defined in RFC 4741

**Comment by sravanmedarapu** [comment]
Thanks for the response @Jainpriyal :)

**Comment by Jainpriyal** [comment]
Closing this issue, please reopen if required.
