### ISSUE TITLE
NPE exception when running command show configuration interfaces | display xml

### ISSUE THREAD

**Issue by lucwillems** [Juniper/netconf-java#13]
i get NPE exception in XML.findValue line 394 with version 1.0.0 and 1.0.2

Java.lang.NullPointerException
        at net.juniper.netconf.XML.findValue(XML.java:394)
        at net.juniper.netconf.NetconfSession.runCliCommand(NetconfSession.java:816)
        at net.juniper.netconf.Device.runCliCommand(Device.java:1008)

i cloned the project and replaced the line on 394 as follow : 
        //prevent NPE
        if (nextElement == null || nextElement.getFirstChild() == null || nextElement.getFirstChild().getNodeValue()== null) {
            return null;
        }

the nextElement.getFirstChild() seems to return NULL

**Comment by peterjhill** [comment]
@lucwillems - If you want to submit a PR against this, we can get it merged. Otherwise I can submit one.

**Comment by peterjhill** [comment]
https://github.com/Juniper/netconf-java/pull/47 will fix this. Mentioned you in the commit comments
