### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Vladislav-Kisliy** [Juniper/netconf-java#24]
` mvn clean package` fails with error:

> [ERROR] Errors: 
> [ERROR]   XMLTest.GIVEN_sampleCliOutputRpc_WHEN_findValueOfSample_THEN_returnValue:46->testFindValue:22 » FileNotFound
> [ERROR]   XMLTest.GIVEN_sampleXML_WHEN_findValueOfSample_THEN_returnValue:38->testFindValue:22 » FileNotFound
> 

It looks like repository doesn't have all required files

PS: Workaround is `mvn -DskipTests clean package`

**Comment by chrisinmtown** [comment]
I don't mean to hijack this issue but it's the most recent one without a reply and I just want to ask, is the netconf-java project still active?  Most recent commit was July 2019.  Thanks.

**Comment by Vladislav-Kisliy** [comment]
@chrisinmtown I hope so, it's a usual situation here. Please have a look on releases - https://github.com/Juniper/netconf-java/releases. This repo hasn't been updated for years but still alive. Just wild guess - main development process is hidden and we can see only releases

**Comment by ydnath** [comment]
@Vladislav-Kisliy @chrisinmtown This repo is driven by community contributions. Your fixes are welcome and will be picked up based on your test results.

**Comment by chrisinmtown** [comment]
I understand how open-source works :) but in this case it seems the repo has a broken build, I hope the person who broke it will also repair it.

**Comment by peterjhill** [comment]
It all works for me on the latest commit:
pjhill-mac:netconf-java pjhill$ mvn clean package
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< net.juniper.netconf:netconf-java >------------------
[INFO] Building netconf-java 2.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ netconf-java ---
[INFO] Deleting /Users/pjhill/Source/netconf-java/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ netconf-java ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/pjhill/Source/netconf-java/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ netconf-java ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 8 source files to /Users/pjhill/Source/netconf-java/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ netconf-java ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ netconf-java ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to /Users/pjhill/Source/netconf-java/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M3:test (default-test) @ netconf-java ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running net.juniper.netconf.XMLTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.087 s - in net.juniper.netconf.XMLTest
[INFO] Running net.juniper.netconf.NetconfSessionTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.113 s - in net.juniper.netconf.NetconfSessionTest
[INFO] Running net.juniper.netconf.LoadExceptionTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in net.juniper.netconf.LoadExceptionTest
[INFO] Running net.juniper.netconf.NetconfExceptionTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in net.juniper.netconf.NetconfExceptionTest
[INFO] Running net.juniper.netconf.DeviceTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in net.juniper.netconf.DeviceTest
[INFO] Running net.juniper.netconf.CommitExceptionTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in net.juniper.netconf.CommitExceptionTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] >>> findbugs-maven-plugin:3.0.5:check (analyze-compile) > :findbugs @ netconf-java >>>
[INFO] 
[INFO] --- findbugs-maven-plugin:3.0.5:findbugs (findbugs) @ netconf-java ---
[INFO] Fork Value is true
[INFO] Done FindBugs Analysis....
[INFO] 
[INFO] <<< findbugs-maven-plugin:3.0.5:check (analyze-compile) < :findbugs @ netconf-java <<<
[INFO] 
[INFO] 
[INFO] --- findbugs-maven-plugin:3.0.5:check (analyze-compile) @ netconf-java ---
[INFO] BugInstance size is 0
[INFO] Error size is 0
[INFO] No errors/warnings found
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ netconf-java ---
[INFO] Building jar: /Users/pjhill/Source/netconf-java/target/netconf-java-2.0.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.999 s
[INFO] Finished at: 2020-02-26T14:54:22-08:00
[INFO] ------------------------------------------------------------------------
pjhill-mac:netconf-java pjhill$

**Comment by peterjhill** [comment]
this could be a case sensitive issue. I'm running my build on a mac on a case insensitive volume. If you are running on a case sensitive volume, that could explain why my tests pass and your fail.

**Comment by peterjhill** [comment]
a quick check, it looks like the case matches on the test file name and the actual file name.

**Comment by peterjhill** [comment]
https://github.com/Juniper/netconf-java/blob/6b0071b5a3393765c907997d2c2d3bf922a09c9f/src/test/java/net/juniper/netconf/XMLTest.java#L43

vs

https://github.com/Juniper/netconf-java/blob/master/src/test/Resources/sampleCliOutputReply.xml

**Comment by ydnath** [comment]
Looks like #28 has the fix. Please check it out.
