### ISSUE TITLE
Question about Yang modules?

### ISSUE THREAD

**Issue by esend7881** [Juniper/netconf-java#29]
(I tried sending this as an email to netconf-automation-hackers@juniper.net but that email seems to block non juniper email address)

Hi There,

I am looking for a NetConf API which I can use to run `get-config` and `edit-config` calls. I am new to netconf and only got some basic things working with netopeer.

Am interested in your API because the netopeer system is a CLI which I have to manually shell in to.

Anyway, I am curious how one would go about installing Yang modules in your system? Or, should I be running another application at the same time (such as sysrepo) and if so, is there any documentation on how to marry up sysrepo and netconf-java?

Appreciate any help,
Eric

**Comment by ydnath** [comment]
@esend7881 
Hello Eric,

Have you reviewed these docs https://www.juniper.net/documentation/en_US/junos/topics/task/operational/netconf-yang-module-obtaining-and-importing.html?

Juniper Yang models are here: https://github.com/Juniper/yang

Do check out and let me know point questions.

Regards,
Dwarakanath

**Comment by esend7881** [comment]
Thanks guys, as it turns out the basis of my question was off. The Yang models were to be installed by my sysrepo. When I did that properly, I was able to run `get-config` and `edit-config` requests through this API there and get the replies I was expecting.
