### ISSUE TITLE
Jar not available in releases

### ISSUE THREAD

**Issue by avierr** [Juniper/netconf-java#34]
Until https://github.com/Juniper/netconf-java/releases/tag/1.0.1
there were jars available but not anymore,

can't even find it on maven: https://search.maven.org/

**Comment by peterjhill** [comment]
That version was never published on maven central. You can git pull that version from github and build it.

**Comment by ydnath** [comment]
Jar will not be released any more due to changes in JDK licensing. The MVN files are updated to resolve the build issues. You can pull from git and build it using your favorite JDK.
