### ISSUE TITLE
RPC XML root attributes statically set?

### ISSUE THREAD

**Issue by KennethGrace** [Juniper/netconf-java#36]
It looks like the following XML automatically encapsulates all our payloads. Without extending "Device", do we have any access to these root element attributes? Thus far I haven't seen anything in "Device" for changing the namespace or adding additional attributes to this default XML. Apologies ahead of time if I'm missing anything.
``` xml
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">

</rpc>
```
Thank you.

**Comment by peterjhill** [comment]
afaik, there are not any methods or parameters that can be passed to change anything in the xml rpc envelope.

I could see adding methods to do this. Is this something you would want to do? I am not sure what you would want to add.

**Comment by KennethGrace** [comment]
I added these methods and created a [pull request](https://github.com/Juniper/netconf-java/pull/37). I'll be closing this issue.
