### ISSUE TITLE
Thread safe Devices and/or message queue?

### ISSUE THREAD

**Issue by KennethGrace** [Juniper/netconf-java#39]
I'm afraid I don't know enough at this point to analyze for myself whether the "NetconfSession" is thread safe. If I share a single "Device" across several threads what issues could I encounter? At a minimum, I expect some confusion around the "getLastRPCReply" method.

I'm thinking of something equivalent to the following. Of course, let's assume these threads could execute in any order at any time in the future.
``` java
Device device = deviceBldr.build()
Thread one = new Thread(()->device.executeRPC("blaface"))
Thread two = new Thread(()->device.executeRPC("blaface"))
...
one.start()
...
two.start()
```
At scale, there could be several threads accessing the same Device instance.

**Comment by peterjhill** [comment]
[NetconfSessions are built using Channels,](https://github.com/Juniper/netconf-java/blob/2d96b82a67feeabdcb930ae68b6148f1f2a04dc8/src/main/java/net/juniper/netconf/NetconfSession.java#L87) which are thread safe. 
https://docs.oracle.com/javase/8/docs/api/java/nio/channels/Channel.html

We always lock and unlock the config before making changes. Think of it as a transactional database where I open a transaction (lock the config) do some work, then commit the transaction (commit and unlock config).

Maybe a refactor (and major version change) would be to move all the methods that act on the netconf session (channel) to the session.

1. Create a Device object (defines how to connect to a device)
2. Using Device object, create a new NetconfSession. (maybe this updates a list of NetconfSessions associated with the Device)
3. use the NetconfSession object to session.execute.RPC("foo")
4. Close the session (remove session from Device Session list)
5. Make sure that the autocloseables for device and netconf session clean up state in each others objects.

Just thinking out loud. 👍

**Comment by KennethGrace** [comment]
So when I lock the config and perform some operation in one thread, will other threads still be able to modify, lock, commit, and unlock the config on their own? This question is more for others at this point, since I imagine <get> and <get-config> operations are fine at any time (via the Channels implementation you mentioned) and that would be the only operation occurring in my different threads. All the config operations are taking place from the same thread in my program.

**Comment by peterjhill** [comment]
others could unlock the config.. it would be pretty rude ;)
if the Device had a list of NetconfSessions associated with the Device, someone could pull off a random session and interact with it.
