### ISSUE TITLE
Maven Build Issue - Test Failure

### ISSUE THREAD

**Issue by mdubois-sst** [Juniper/netconf-java#44]
I am having an issue building the jar with Maven. I have the latest code from master. When I run mvn package I get the following test error

```
[ERROR] Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.995 s <<< FAILURE! - in net.juniper.netconf.NetconfSessionTest
[ERROR] GIVEN_executeRPC_WHEN_lldpRequest_THEN_correctResponse(net.juniper.netconf.NetconfSessionTest)  Time elapsed: 1.567 s  <<< FAILURE!
org.junit.ComparisonFailure:
expected:<...nos" message-id="3">[
    <lldp-neighbors-information junos:style="brief">
        <lldp-neighbor-information>
            <lldp-local-port-id>xe-0/0/9:1</lldp-local-port-id>
            <lldp-local-parent-interface-name>ae51</lldp-local-parent-interface-name>
            <lldp-remote-chassis-id-subtype>Mac address</lldp-remote-chassis-id-subtype>
            <lldp-remote-chassis-id>00:00:00:80:1e:00</lldp-remote-chassis-id>
            <lldp-remote-port-description>ethernet  6/1</lldp-remote-port-description>
            <lldp-remote-system-name>test.system.new</lldp-remote-system-name>
        </lldp-neighbor-information>
]   </lldp-neighbors-information>
</rpc-reply>
> but was:<...nos" message-id="3">[
    <lldp-neighbors-information junos:style="brief">
        <lldp-neighbor-information>
            <lldp-local-port-id>xe-0/0/9:1</lldp-local-port-id>
            <lldp-local-parent-interface-name>ae51</lldp-local-parent-interface-name>
            <lldp-remote-chassis-id-subtype>Mac address</lldp-remote-chassis-id-subtype>
            <lldp-remote-chassis-id>00:00:00:80:1e:00</lldp-remote-chassis-id>
            <lldp-remote-port-description>ethernet  6/1</lldp-remote-port-description>
            <lldp-remote-system-name>test.system.new</lldp-remote-system-name>
        </lldp-neighbor-information>
    </lldp-neighbors-information>]
</rpc-reply>
>
        at net.juniper.netconf.NetconfSessionTest.GIVEN_executeRPC_WHEN_lldpRequest_THEN_correctResponse(NetconfSessionTest.java:182)

[INFO] Running net.juniper.netconf.XMLTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 s - in net.juniper.netconf.XMLTest
[INFO] 
[INFO] Results:
[INFO]
[ERROR] Failures: 
[ERROR]   NetconfSessionTest.GIVEN_executeRPC_WHEN_lldpRequest_THEN_correctResponse:182 expected:<...nos" message-id="3">[
    <lldp-neighbors-information junos:style="brief">
        <lldp-neighbor-information>
            <lldp-local-port-id>xe-0/0/9:1</lldp-local-port-id>
            <lldp-local-parent-interface-name>ae51</lldp-local-parent-interface-name>
            <lldp-remote-chassis-id-subtype>Mac address</lldp-remote-chassis-id-subtype>
            <lldp-remote-chassis-id>00:00:00:80:1e:00</lldp-remote-chassis-id>
            <lldp-remote-port-description>ethernet  6/1</lldp-remote-port-description>
            <lldp-remote-system-name>test.system.new</lldp-remote-system-name>
        </lldp-neighbor-information>
]   </lldp-neighbors-information>
</rpc-reply>
> but was:<...nos" message-id="3">[
    <lldp-neighbors-information junos:style="brief">
        <lldp-neighbor-information>
            <lldp-local-port-id>xe-0/0/9:1</lldp-local-port-id>
            <lldp-local-parent-interface-name>ae51</lldp-local-parent-interface-name>
            <lldp-remote-chassis-id-subtype>Mac address</lldp-remote-chassis-id-subtype>
            <lldp-remote-chassis-id>00:00:00:80:1e:00</lldp-remote-chassis-id>
            <lldp-remote-port-description>ethernet  6/1</lldp-remote-port-description>
            <lldp-remote-system-name>test.system.new</lldp-remote-system-name>
        </lldp-neighbor-information>
    </lldp-neighbors-information>]
</rpc-reply>
>
[INFO]
[ERROR] Tests run: 21, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.642 s
[INFO] Finished at: 2021-02-09T14:21:37-05:00
[INFO] ------------------------------------------------------------------------


```

**Comment by Vladislav-Kisliy** [comment]
Hi. It works for me fine. What OS do you use?

**Comment by Sahilmehta2007** [comment]
Getting this same error.

I am using Windows 10.
Java :  jdk1.8.0_271



>
        at net.juniper.netconf.NetconfSessionTest.GIVEN_executeRPC_WHEN_lldpRequest_THEN_correctResponse(NetconfSessionTest.java:182)

[INFO] Running net.juniper.netconf.XMLTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 s - in net.juniper.netconf.XMLTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   NetconfSessionTest.GIVEN_executeRPC_WHEN_lldpRequest_THEN_correctResponse:182 expected:<...nos" message-id="3">[
    <lldp-neighbors-information junos:style="brief">
        <lldp-neighbor-information>
            <lldp-local-port-id>xe-0/0/9:1</lldp-local-port-id>
            <lldp-local-parent-interface-name>ae51</lldp-local-parent-interface-name>
            <lldp-remote-chassis-id-subtype>Mac address</lldp-remote-chassis-id-subtype>
            <lldp-remote-chassis-id>00:00:00:80:1e:00</lldp-remote-chassis-id>
            <lldp-remote-port-description>ethernet  6/1</lldp-remote-port-description>
            <lldp-remote-system-name>test.system.new</lldp-remote-system-name>
        </lldp-neighbor-information>
]   </lldp-neighbors-information>
</rpc-reply>
> but was:<...nos" message-id="3">[
    <lldp-neighbors-information junos:style="brief">
        <lldp-neighbor-information>
            <lldp-local-port-id>xe-0/0/9:1</lldp-local-port-id>
            <lldp-local-parent-interface-name>ae51</lldp-local-parent-interface-name>
            <lldp-remote-chassis-id-subtype>Mac address</lldp-remote-chassis-id-subtype>
            <lldp-remote-chassis-id>00:00:00:80:1e:00</lldp-remote-chassis-id>
            <lldp-remote-port-description>ethernet  6/1</lldp-remote-port-description>
            <lldp-remote-system-name>test.system.new</lldp-remote-system-name>
        </lldp-neighbor-information>
    </lldp-neighbors-information>]
</rpc-reply>
>
[INFO]
[ERROR] Tests run: 21, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.623 s
[INFO] Finished at: 2021-05-28T12:58:09+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project netconf-java: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\932478\Juniper-NetConf-java\netconf-java\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[error.md](https://github.com/Juniper/netconf-java/files/6559104/error.md)



I am using Windows 10.
Java :  jdk1.8.0_271

**Comment by peterjhill** [comment]
Oh, interesting. I bet this is a LF/CR issue. Let me make an issue.

**Comment by peterjhill** [comment]
Yes. Definitely a problem with line endings.
I have repro'd the issue on my windows box. (gaming machine for the win).

An easy fix.

**Comment by peterjhill** [comment]
PR to fix this issue: https://github.com/Juniper/netconf-java/pull/47
