### ISSUE TITLE
Advice to email  netconf-automation-hackers@juniper.net seems incorrect

### ISSUE THREAD

**Issue by GregDThomas** [Juniper/netconf-java#46]
On the README, it says

> To report bug-fixes, issues, suggestions, please contact netconf-automation-hackers@juniper.net

If you attempt to email this address, a reply is received:

> The group netconf-automation-hackers only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.

I guess raising a GitHub issue or Pull request is the way forward, but want to know if there is a better way forward?

**Comment by ydnath** [comment]
Please submit a pull request if you have code changes to be reviewed. Else, please raise a GitHub issue.
