### ISSUE TITLE
Thread-Safe RPC Requests

### ISSUE THREAD

**Issue by beserb** [Juniper/netconf-java#64]
In NetconSession class, I see that getRpcReply method writes and reads directly from device session output and input stream (stdOutStreamToDevice and stdInStreamFromDevice). If I am not wrong, this means in case multiple requests from different threads are sent in the same session, responses might get mixed (or even corrupt as there is no control like "read until first prompt").

As far as I see, the only way to guarantee thread-safe behavior is to create a new session per request (device.connect, device.executeRpc, device.close). Is that a correct observation?

**Comment by GregDThomas** [comment]
Yes - you would need multiple sessions. 

I guess it would be theoretically possible to sequence the output stream (you need to ensure the first request was completed before you started sending the second), and use the identifiers in the message to identify which response was sent to which request. However, given the model of NETCONF is very much request/response pairs, I'm not sure any perceived benefits of this outweigh the increase in complexity that the code would require.

**Comment by beserb** [comment]
Thanks for the answer. I close this issue.
