### ISSUE TITLE
is to passible to change the Password and add the new user 

### ISSUE THREAD

**Issue by sravanmedarapu** [Juniper/netconf-java#8]
Hi There,

When I am using commands to change the password of current user. I getting the some kind of interface questions like "Enter password: and Retype the password:"  to conform the given password

So can we do this using Java API, I tried something like "device.setPassword("newPassword");" but it throwing an exception. And I wanted to add new user.

Can someone guide me on this.

Thanks in Advance 
Sravan Medarapu

**Comment by shermdog** [comment]
Hi @sravanmedarapu,

To make any changes to Junos you need to modify the configuration.  The setPassword() function you are using is to set the password the framework is using to connect via NETCONF.

Please see this example for more information:
https://github.com/Juniper/netconf-java/blob/master/examples/EditConfiguration.java

-Rick
