### ISSUE TITLE
Is it possible to execute the Configuration scripts in the parallel using multi threading ?

### ISSUE THREAD

**Issue by sravanmedarapu** [Juniper/netconf-java#9]
Hi All,

I have a requirement to execute the configuration related code(adding and deleting access-lists) in parallel, I am using multi threading concept to execute the commands.

but only 1 st thread's device instance is able to execute the commands , from 2 nd thread instance device.loadSetConfiguration("command") is  throwing "Load operation returned error" [ here I am creating different Device object for each thread]

Can some help me on this, Does JunOS support parallel execution .

Device I am using Juniper Ex 4200 series 480PoE+.

Thanks in Advance
Sravan Medarapu

**Comment by Jainpriyal** [comment]
Hi Sravan,

Junos supports parallel execution. It should also work fine with netconf-java API, I am looking into the issue.
Can you please post the sample script that you are running for parallel execution using multithreading.

**Comment by sravanmedarapu** [comment]
Hi Jainpriyal,

Thanks for the response, Please find the below sample code 

Note: 
My requirement is to add the access-lists(filters) to the device in parallel.


    public class DeviceConn {
	public static void main(String[] args) throws ParserConfigurationException, IOException,    SAXException {
	int i=1;
	ArrayList<Device> devList=new ArrayList<Device>();
	for( i=1;i<10;i++){
		try{
		     JunOS_Threads thread=new JunOS_Threads();
		     thread.start();
		}catch(Exception e){
			System.out.println("error:"+e.getMessage());
		}
	}
	}
}


	
	class JunOS_Threads extends Thread{
        @Override
	public void run() {
		try{
			Device dev=new Device("192.168.222.1","test","test@123",null);
			dev.connect();
			System.out.println("Connection established");
			dev.loadSetConfiguration("delete vlans TEST-2 filter");
			dev.loadSetConfiguration("set firewall family ethernet-switching filter block-to-server term 1 from destination-address 192.168.222.0/24");
			dev.loadSetConfiguration("set firewall family ethernet-switching filter block-to-server term 1 then accept");
            dev.loadSetConfiguration("set vlans TEST filter input block-to-server");
			dev.commit();
		}catch(Exception e){
			System.out.println("error in th class:"+e.getMessage());
		}
	}
}


run method will have the different set of commands for each therad

Please let me know if you need any other information.


Thanks
Sravan

**Comment by Jainpriyal** [comment]
Hi Sravan,

You can try using private configuration mode for running configuration command in parallel, if you are running different sets of command for each thread.
please refer:
https://www.juniper.net/documentation/en_US/junos12.1/topics/topic-map/netconf-java-toolkit-configuration-requests.html
http://www.juniper.net/documentation/en_US/junos14.2/topics/task/configuration/junos-cli-configure-private-configuration-changes-updating.html

But you can not multithread "configuration command" in normal mode for one device.
For loading configuration it first locks the device. In multithreading, device is locked by first thread so when other threads try to lock the device it will throw “Load Error”.

Thanks
Priyal

**Comment by sravanmedarapu** [comment]
Hi Jainpriyal,
Thanks for the response, unfortunately  "private configuration mode" also didn't work for me below is the sample code snippet

    class JunOS_Threads extends Thread{
	String cmd="";
	JunOS_Threads(String cmd){
		this.cmd=cmd;
	}
	@Override
	public void run() {
		try{
			Device dev=new Device("192.168.222.1","test","test@123",null);
			dev.connect();
			dev.openConfiguration("private");
			dev.loadSetConfiguration(cmd);
			dev.commit();
			dev.close();
			
		}catch(Exception e){
			System.out.println("Error:"+e.getMessage());
		}
	}
}



Error I am seeing "Commit operation returned error"

If I remove the dev.commit(); statement it is working fine but command is not reflected to the Device . and even when I explicitly use commit() method after adding all configuration statements also its not reflected.

Can you please guide me on this ?

Please let me know if you need any other information on the same.

Thanks
Sravan Medarapu

**Comment by Jainpriyal** [comment]
Hi Sravan,

Please use latest netconf-java version, openConfiguration("private") has some problem and it got fixed in latest release https://github.com/Juniper/netconf-java/releases/tag/1.0.1 

If you don't want to upgrade then please use ` <private/>` as argument in openConfiguration() command instead of "private". https://github.com/Juniper/netconf-java/issues/7

**Comment by sravanmedarapu** [comment]
Hi Jainpriyal,

I am using latest version of netconf-java (V1.0.1) and I could see all configuration actions are happening in a private mode only but when use commit() method  I am seeing the exception .


Even I have tried by using   < private/ >  still I am seeing the same issue.

Thanks
Sravan

**Comment by Jainpriyal** [comment]
Hi Sravan,

For which configuration your commit is failing, Is it failing for all threads, or you are able to commit for one thread but for others its failing.

Also can you verify manually from, that the configure command you are trying to load is committing properly. For example, If you are trying to delete vlan green, but if it is not there then it might give error. 

If possible can you give the list of configurations that you are trying to load from different threads.If you are doing changes in the same load command from different threads then it will give error.

**Comment by sravanmedarapu** [comment]
Hi Jainpriyal,

here is the sample commands I am executing for each thread

thread1: 
        set firewall family ethernet-switching filter block-to-server-vlan-VLAN-A term 1 from destination-address 192.168.111.0/24

thread2:
       set firewall family ethernet-switching filter block-to-server-vlan-VLAN-A term 1 then accept

thread3:
        set firewall family ethernet-switching filter block-to-server-vlan-VLAN-A term DENY from destination-address 192.168.245.0/24

thread4: 
    set firewall family ethernet-switching filter block-to-server-vlan-VLAN-A term DENY then discard

thread5:
  set firewall family ethernet-switching filter block-to-server-vlan-VLAN-A term ANY then accept

And I can see only 1 thread able to commit successfully and rest of the threads are throwing following exception

      Error Message:Commit operation returned error.
         net.juniper.netconf.CommitException: Commit operation returned error.
	at net.juniper.netconf.NetconfSession.commit(NetconfSession.java:671)
	at net.juniper.netconf.Device.commit(Device.java:860)

**Comment by shermdog** [comment]
Hi Sravan,

I highly advise against this type of processing of persistent changes.  Junos is not well suited for this type of model and that many commits will make managing the system long term **very** difficult.

Furthermore you'll be losing a **lot** of performance by this model as each commit will take some time - negating the entire reason why you'd want to do multiple threads.

You should look at using configuration templates to iterate your data and apply the configuration changes in bulk.
http://velocity.apache.org/

-Rick

**Comment by sravanmedarapu** [comment]
Its the requirement of the project, below is the client requirement

Client is having different Templates(bulk Templates) which has to be invoked before starting the test case but rest of the test steps should not wait till the completion of the total commit i.e. something like Asynchronous execution .

Thanks for the suggestion :)

Can you please guide me for these queries as well (https://github.com/Juniper/netconf-java/issues/10) 


Thanks 
Sravan Medarapu

**Comment by ganeshnalawade** [comment]
When a commit is issued it locks the database till commit is complete.
It seems when commit issued from thread-1 is in progress another commit is issued from thread-2 thus failing the commit process for thread-2. In your exception handling add sufficient amount of delay and issue commit again.
As @shermdog suggested this is not a optimized approach.

**Comment by Jainpriyal** [comment]
There are restrictions on committing a private copy. For example, the commit fails if the regular candidate configuration is locked by another user or application, or if it includes uncommitted changes made since the private copy was created. For more information, http://www.juniper.net/techpubs/en_US/junos14.1/information-products/topic-collections/junos-xml-management-protocol-guide/index.html?id-10572066.html

Instead of committing your configurations inside thread, can you please try by just loading the configuration in thread and then committing and closing each session of device explicitly.

In private mode all the threads are trying to commit at the same time, hence only one will get the lock and others will give database locked, commit error.

Below is the sample code, it worked for me for loading above mentioned configuration :
```
public class CallableDemo {
   public static void main(String[] args) throws InterruptedException, ExecutionException, IOException, CommitException {
	   ExecutorService service =  Executors.newSingleThreadExecutor();
           String[] commands = new String[100];
           commands[0]= "set firewall family ethernet-switching filter block-to-server-vlan-VLAN-A term 1 from destination-address 192.168.111.0/24";
           commands[1]= "set firewall family ethernet-switching filter block-to-server-vlan-VLAN-A term 1 then accept";
           commands[2]= "set firewall family ethernet-switching filter block-to-server-vlan-VLAN-A term DENY from destination-address 192.168.245.0/24";
           commands[3]= "set firewall family ethernet-switching filter block-to-server-vlan-VLAN-A term DENY then discard";
           commands[4]= "set firewall family ethernet-switching filter block-to-server-vlan-VLAN-A term ANY then accept";
           int i=0;
           for (i=0;i<5;i++){
           Execute_config ex = new Execute_config("router1",commands[i]);
	   Future<Device> future = service.submit(ex);
	   Device result = future.get();
	   System.out.println(result);
           try{
           result.commit();
           }
           catch(Exception e){
               System.out.print("Exception occurred");
           }
           result.close();
           }
   }
}
class Execute_config implements Callable<Device> {
        int i=0;
	private String deviceName;
        private String command;
        
        public Execute_config(String d, String com){
   	        deviceName= d;
                command=com;
        }
	@Override
	public Device call() throws Exception {
            
            Device dev = new Device(deviceName,"abc","xyz",null);
            dev.connect();
            dev.openConfiguration("private");
            System.out.println("Device value is");
            System.out.print(dev);
            try {
             dev.loadSetConfiguration(command);           
         } catch(Exception e) {
             System.out.println("inside catch block \n");
             System.out.println(e.getMessage());
            
         }    
            return dev;
	}
}

```

**Comment by sravanmedarapu** [comment]
Thanks @ganeshnalawade and @Jainpriyal for the detailed response, I understand the technical aspect.

@Jainpriyal thanks for the detailed code, seems like though we are triggering different threads for loading the configuration but we are triggering another thread only after completion of the current thread

       Device result = future.get();

the above statement(thread triggering) will wait until call method returns dev object, which means completion of the current thread. Please correct me if I am wrong.

However I am Ok with the technical reason behind the limitation. 

Now I would like to capture the below details 

• Traffic monitoring

• Network Packet Capturing(Some thing like how much data/Packets has been transferred from one port to another port ) 


Can you please help me on this, I post a question here for this discussion (https://github.com/Juniper/netconf-java/issues/10)


Thanks in Advance 
Sravan Medarapu

**Comment by Jainpriyal** [comment]
Please see the response in https://github.com/Juniper/netconf-java/issues/10
Closing this issue, reopen if required.
